source "http://rubygems.org"

gem "rake"
gem "jeweler"
gem "cucumber"
gem "aruba", ">= 0.2.0"
gem "autotest"
gem "rspec-mocks", :path => "."
gem "rspec-core", :path => "../rspec-core"
gem "rspec-expectations", :path => "../rspec-expectations"
gem "ruby-debug"
